### ISSUE TITLE
About the issue with RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by 520jz** [zju3dv/PGSR#56]
Hello authors! Thank you very much for your excellent work
I'd like to ask, why does calling rasterizer or render multiple times get CUDA error: an illegal memory access was encountered?
For example, in the original PGSR code, when the return_plan hyperparameter is false or true, Rasterizer will only be called once, that is, rasterization will only be performed once.
![image](https://github.com/user-attachments/assets/395b774c-ac18-4f46-a580-992df8f18f2b)

If I call rasterizer after rasterizer now, for example I want to render a depth map with the z-value of a Gaussian ellipsoid
![image](https://github.com/user-attachments/assets/d572925c-8588-4b4f-b9b3-32adcb5654ec)

But in the end, after the render ends, the image should be a tensor array of C H W, but it becomes an object at this point. This leads to an error message when calculating a loss: ImageAn Illegal Memory Access was encountered
![image](https://github.com/user-attachments/assets/be3675b9-46c9-4196-b8de-0c7ea8f6652e)

![image](https://github.com/user-attachments/assets/c9973f76-67a2-45a7-8aaf-ef31b8f5c014)

In the red part below, the image becomes an object after the second rasterizer is called, and it stands to reason that the two rasterizers should not affect each other, and I remember that Gaussian-shader and GaussianPro have called rasterizer many times without similar problems.
![image](https://github.com/user-attachments/assets/65c3bbcb-2308-4059-a62d-8122d0eda61b)

In fact, even before the render function is returned at the end of the run, when you get the rotation or scale in the middle of the get_normal, you will find that it has become a string of addresses. Instead of the tensor array, it seems that the variables of the entire Gaussian-model are affected.
![image](https://github.com/user-attachments/assets/c73e16d1-bdb8-4985-82fa-70a25bb89bd8)

**Comment by danpeng2** [comment]
Hello, multiple calls to the rasterizer are fine. Within the same training iteration, we also call the rasterizer again for multi-view constraints. In your second call, the channel dimension of depth_z needs to be consistent with rgb and should be 3-dimensional.

**Comment by 520jz** [comment]
Thank you very much for your reply, my problem has been solved, because some negligence caused the parameters passed in the second rasterizer to be inconsistent with the first one.
